---
- name: load vars
  include_vars:
    file: main.yml

- name: redeploy {{ project_name }}
  vars:
    action: 'deploy'
    common_run: True
  include_role:
    name: '{{ project_name }}'

- name: remove {{ project_name }}
  include_role:
    name: util/kolla
    tasks_from: remove
  when: inventory_hostname in groups['decrease']
