---
- name: remove resources
  include: remove.yml

- name: deploy resource
  vars:
    action: 'deploy'
    role_rabbitmq_cluster_cookie: '{{ rabbitmq_cluster_cookie }}'
    role_rabbitmq_cluster_port: '{{ rabbitmq_cluster_port }}'
    role_rabbitmq_epmd_port: '{{ rabbitmq_epmd_port }}'
    role_rabbitmq_groups: rabbitmq
    role_rabbitmq_management_port: '{{ rabbitmq_management_port }}'
    role_rabbitmq_monitoring_password: '{{ rabbitmq_monitoring_password }}'
    role_rabbitmq_monitoring_user: '{{ rabbitmq_monitoring_user }}'
    role_rabbitmq_password: '{{ rabbitmq_password }}'
    role_rabbitmq_port: '{{ rabbitmq_port }}'
    role_rabbitmq_user: '{{ rabbitmq_user }}'
    common_run: True
  include_role:
    name: rabbitmq
